version: '3.1'

services:

  db:
    image: postgres:14
    restart: always
    ports:
      - "14323:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: garage
